import http from 'k6/http';
import { check, sleep } from 'k6';

export const options = {
  scenarios: {
    user_journey: {
      executor: 'ramping-vus',
      startVUs: 5,
      stages: [
        { duration: '20s', target: 20 },
        { duration: '30s', target: 50 },
        { duration: '30s', target: 100 },
        { duration: '20s', target: 0 },
      ],
      gracefulRampDown: '10s',
    },
  },
  thresholds: {
    http_req_failed: ['rate<0.05'],
    http_req_duration: ['p(95)<1500'],
  },
};

const API_URL = __ENV.API_URL || 'http://localhost:3000/graphql';

function sendGQL(query, variables = {}) {
  return http.post(API_URL, JSON.stringify({ query, variables }), {
    headers: { 'Content-Type': 'application/json' },
  });
}

export default function () {
  // 1. Query all projects
  const projectsRes = sendGQL(`
    query {
      projects {
        id
        name
        key
      }
    }
  `);

  check(projectsRes, {
    'get projects succeeded': (r) => {
      try {
        const body = r.json();
        return !body.errors && body.data?.projects?.length > 0;
      } catch (e) {
        return false;
      }
    },
  });

  const projects = projectsRes.json()?.data?.projects || [];
  if (projects.length === 0) {
    sleep(1);
    return;
  }

  const targetProject = projects[Math.floor(Math.random() * projects.length)];

  // 2. Query releases for selected project
  const listRes = sendGQL(
    `
    query GetReleases($filter: FilterReleasesInput) {
      releases(filter: $filter) {
        id
        name
        version
        status
      }
    }
  `,
    { filter: { projectId: targetProject.id } },
  );

  check(listRes, {
    'get project releases succeeded': (r) => {
      try {
        const body = r.json();
        return !body.errors;
      } catch (e) {
        return false;
      }
    },
  });

  // 3. Create a unique test release
  const randomVer = `v9.${Math.floor(Math.random() * 900) + 100}.${Math.floor(Math.random() * 1000)}`;
  const createRes = sendGQL(
    `
    mutation CreateRelease($input: CreateReleaseInput!) {
      createRelease(input: $input) {
        id
        name
        version
        steps {
          id
          title
          status
        }
      }
    }
  `,
    {
      input: {
        projectId: targetProject.id,
        name: `Load Test Release ${randomVer}`,
        version: randomVer,
        description: 'Automated performance benchmark release',
        notes: 'Generated by k6 full-flow workload runner',
      },
    },
  );

  const createdRelease = createRes.json()?.data?.createRelease;
  check(createRes, {
    'create release succeeded': (r) => {
      try {
        return !r.json().errors && createdRelease?.id;
      } catch (e) {
        return false;
      }
    },
  });

  if (createdRelease?.id) {
    const releaseId = createdRelease.id;

    // 4. Update step if steps were auto-generated
    if (createdRelease.steps && createdRelease.steps.length > 0) {
      const stepId = createdRelease.steps[0].id;
      const stepRes = sendGQL(
        `
        mutation UpdateStep($input: UpdateReleaseStepInput!) {
          updateReleaseStep(input: $input) {
            id
            status
          }
        }
      `,
        {
          input: {
            id: stepId,
            status: 'COMPLETED',
          },
        },
      );

      check(stepRes, {
        'update step succeeded': (r) => {
          try {
            return !r.json().errors;
          } catch (e) {
            return false;
          }
        },
      });
    }

    // 5. Update release notes and status
    const updateRes = sendGQL(
      `
      mutation UpdateRelease($input: UpdateReleaseInput!) {
        updateRelease(input: $input) {
          id
          status
          notes
        }
      }
    `,
      {
        input: {
          id: releaseId,
          status: 'READY_FOR_DEPLOYMENT',
          notes: 'Pre-flight checks passed under load test conditions.',
        },
      },
    );

    check(updateRes, {
      'update release succeeded': (r) => {
        try {
          return !r.json().errors;
        } catch (e) {
          return false;
        }
      },
    });

    // 6. Delete the test release to keep db clean
    const deleteRes = sendGQL(
      `
      mutation DeleteRelease($id: ID!) {
        deleteRelease(id: $id)
      }
    `,
      { id: releaseId },
    );

    check(deleteRes, {
      'delete release succeeded': (r) => {
        try {
          return !r.json().errors && r.json().data?.deleteRelease === true;
        } catch (e) {
          return false;
        }
      },
    });
  }

  sleep(1);
}
